name: Compilar SpaceXit PC
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configurar MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Gerar Projeto e Compilar
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release

      - name: Enviar EXE para Download
        uses: actions/upload-artifact@v3
        with:
          name: SpaceXit_PC_Edition
          path: build/Release/SpaceXit_PC.exe
