name: Build SpaceXit PC
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Compilador Windows (MSVC)
        uses: ilammy/msvc-dev-cmd@v1

      - name: Compilar SpaceXit EXE
        run: |
          cl.exe /EHsc main.cpp /Fe:SpaceXit_PC.exe user32.lib gdi32.lib shell32.lib
        # O comando /Fe: define o nome exato do arquivo de saida

      - name: Enviar para Download
        uses: actions/upload-artifact@v4
        with:
          name: SpaceXit-PC-Executavel
          path: SpaceXit_PC.exe
